# cloudbuild.yaml
images:
  - gcr.io/$PROJECT_ID/puppeteer-cookie-service

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/puppeteer-cookie-service
      - -f
      - Dockerfile
      - .

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
